version: '3'
services:
  django-server:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/usr/src/start-server.sh", "--debug"]
    container_name: django-server
    networks:
      - default
    env_file: .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.anitrend.rule=Host(`${HOST}`)"
      - "traefik.http.routers.anitrend.entrypoints=web,websecure"
      - "traefik.http.routers.anitrend.service=anitrend"
      - "traefik.http.routers.anitrend.tls=true"
      - "traefik.http.routers.anitrend.tls.certresolver=staging"
      - "traefik.http.services.anitrend.loadbalancer.server.port=${PORT}"

  django-q:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/usr/src/start-q.sh"]
    container_name: django-q
    networks:
      - default
    env_file: .env

networks:
  default:
    name: traefik
    external: true
