[tool.poetry]
name = "anitrend"
version = "0.2.1"
description = ""
authors = ["Maxwell <wax911@users.noreply.github.com>"]
license = "GPL"
readme = "README.md"
packages = []

[tool.poetry.dependencies]
python = "^3.13"
uplink = "0.10.0"
requests = "2.33.0"
marshmallow = "4.2.3"
python-decouple = "3.8"
django-cors-headers = "4.9.0"
django = "6.0.3"
dependency_injector = "4.49.0"
gunicorn = "25.3.0"
ua-parser = "1.0.1"
growthbook = "2.2.0"
brotli = "1.2.0"
pytz = "^2024.2"
strawberry-graphql-django = "^0.82.0"
django-choices-field = "^4.0.0"
uvicorn = "^0.42.0"
starlette = "^1.0.0"
setuptools = "^82.0.0"
marshmallow-dataclass = "^8.7.1"
opentelemetry-sdk = "^1.34.1"
opentelemetry-instrumentation-django = "^0.55b1"
opentelemetry-instrumentation-asgi = "^0.55b1"
opentelemetry-instrumentation-logging = "^0.55b1"
opentelemetry-exporter-otlp-proto-grpc = "^1.34.1"
opentelemetry-instrumentation-requests = "^0.55b1"

[tool.poetry.group.dev.dependencies]
pytest = "^9.0.0"
pytest-django = "^4.10.0"

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.core.masonry.api"
