[tool.poetry]
name = "anitrend-relations-py"
version = "0.1.0"
description = ""
authors = ["Maxwell <mxt.developer@gmail.com>"]
license = "GPL"
readme = "README.md"
packages = [{ include = "anitrend_relations_py" }]

[tool.poetry.dependencies]
python = "^3.10"
uplink = "0.9.7"
requests = "2.31.0"
marshmallow = "3.20.1"
python-decouple = "3.8"
django-filter = "23.2"
graphene-django = "3.1.3"
graphene-django-extras = { git = "https://github.com/wax911/graphene-django-extras.git", tag = "0.1.0" }
django-cors-headers = "4.2.0"
graphene = "3.3"
django-enumfield = "3.1"
django-graphql-playground = "1.0"
django-extensions = "3.2.3"
django-q2 = "1.5.4"
django = "4.2.4"
dependency_injector = "4.41.0"
serde = "0.9.0"
gunicorn = "21.2.0"
psycopg2-binary = "2.9.7"
reactivex = "4.0.4"
pyxtension = "1.16.1"
ua-parser = "0.18.0"
growthbook = "1.0.0"
rollbar = "0.16.3"
logtail-python = "0.2.6"

[tool.poetry.group.dev.dependencies]
flake8 = "6.0.0"
pytest = "7.4.0"
pytest-cov = "4.1.0"

[tool.poetry.group.lint.dependencies]
isort = "5.10.1"
black = "22.8.0"
flake8 = "5.0.4"
mypy = "0.971"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "app.settings.development"
python_files = ["tests.py", "tests/*.py"]
addopts = "-p no:cacheprovider"

[tool.isort]
profile = "black"
known_first_party = "anitrend-relations-py"

[tool.coverage.run]
branch = true
source = ["anitrend-relations-py"]

[tool.coverage.report]
ignore_errors = true

[tool.poetry.plugins."flake8.extension"]
DM = "flake8_django_migrations:Plugin"

[tool.coverage.report]
exclude_lines = [
    'if __name__ == "__main__":'
]

[tool.semantic_release]
branch = "develop"
version_variable = "app/__init__.py:__version__"
version_toml = "pyproject.toml:tool.poetry.version"
version_source = "tag"
commit_version_number = true # required for version_source = "tag"
commit_message = "{version} [skip ci]" # skip triggering ci pipelines for version commits
tag_commit = true
upload_to_pypi = false
upload_to_release = false
hvcs = "github" # gitlab is also supported (hvcs = host version control system)
