# Generated by Django 3.2.2 on 2021-05-09 14:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anidb', models.IntegerField(null=True)),
                ('anilist', models.IntegerField(null=True)),
                ('animeplanet', models.CharField(max_length=256, null=True)),
                ('kitsu', models.IntegerField(null=True)),
                ('mal', models.IntegerField(null=True)),
                ('notify', models.CharField(max_length=25, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('TV', 'TV'), ('Movie', 'Movie'), ('OVA', 'OVA'), ('ONA', 'ONA'), ('Special', 'Special')], max_length=12)),
                ('episodes', models.IntegerField()),
                ('status', models.CharField(choices=[('FINISHED', 'FINISHED'), ('CURRENTLY', 'CURRENTLY'), ('UPCOMING', 'UPCOMING'), ('UNKNOWN', 'UNKNOWN')], max_length=12)),
                ('picture', models.CharField(max_length=128)),
                ('thumbnail', models.CharField(max_length=128)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('relation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.relation')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anidb', models.IntegerField(null=True)),
                ('anilist', models.IntegerField(null=True)),
                ('animeplanet', models.CharField(max_length=256, null=True)),
                ('kitsu', models.IntegerField(null=True)),
                ('mal', models.IntegerField(null=True)),
                ('notify', models.CharField(max_length=25, null=True)),
                ('tvdb', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.series')),
            ],
            options={
                'ordering': ('title',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.series')),
            ],
            options={
                'ordering': ('title',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='series',
            name='source',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.source'),
        ),
    ]
