schema: schema.graphql
extensions:
  endpoints:
    Default GraphQL Endpoint:
      url: http://localhost:8000/graphql/
      headers:
        User-Agent: "JS GraphQL"
        Accept: "*/*"
        HOST: "localhost"
        Accept-Encoding: "gzip, deflate, br"
        Accept-Language: "en-GB,en-US;q=0.9,en;q=0.8"
        Content-Type: "application/json"
      introspect: true
