"""
Django settings for app project in development env

Generated by 'django-admin startproject' using Django 3.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from .common import *

ALLOWED_HOSTS = ["localhost", "127.0.0.1", "10.0.2.2"]

DATA_UPLOAD_MAX_NUMBER_FIELDS = 1500

Q_CLUSTER = {
    "name": "edge-sync",
    "orm": "default",
    'workers': 2,
    "recycle": 250,
    "timeout": 1800,
    "retry": 3600,
    "label": "worker",
}

DATABASES = {
    "default": {
        "ENGINE": 'django.db.backends.postgresql_psycopg2',
        "NAME": config("DJANGO_DATABASE_NAME", cast=str),
        "USER": config("DJANGO_DATABASE_USER", cast=str),
        "PASSWORD": config("DJANGO_DATABASE_PASSWORD", cast=str),
        "HOST": config("DJANGO_DATABASE_HOST", cast=str),
        "PORT": config("DJANGO_DATABASE_PORT", cast=int),
    },
}

LANGUAGE_CODE = "en-uk"

TIME_ZONE = "Africa/Johannesburg"
