name: django-cd

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build against'
        required: true
        default: 'latest'
  push:
    branches:
      - develop
    tags: "*"

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set Tag
        id: set-tag
        run: |
          if [[ -n "${{ github.event.inputs.tag }}" ]]; then
            echo "::set-output name=tag::${{ github.event.inputs.tag }}"
          elif [[ "${{ github.ref }}" =~ ^refs/tags/ ]]; then
            echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"
          else
            echo "::set-output name=tag::latest"
          fi
      - name: Show Generated Tag Value
        run: |
          echo "Tag value: ${{ steps.set-tag.outputs.tag }}"
      - name: Build and Push Docker Image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 . \
          --output type=docker \
          --tag ghcr.io/anitrend/anitrend:${{ steps.set-tag.outputs.tag }} \
          --cache-from type=registry,ref=ghcr.io/anitrend/anitrend:cache,mode=max \
          --cache-to type=registry,ref=ghcr.io/anitrend/anitrend:cache
          docker push ghcr.io/anitrend/anitrend:${{ steps.set-tag.outputs.tag }}
        working-directory: .
