name: django-cd

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build against'
        required: true
        default: 'latest'  # Default tag if not provided
  push:
    tags: "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build . --tag ghcr.io/${{ github.repository }}/anitrend:${{ github.event.inputs.tag }} .
        working-directory: .

      - name: Push Docker Image to GitHub Packages
        run: docker push ghcr.io/${{ github.repository }}/anitrend:${{ github.event.inputs.tag }}

